# Connector Plugin Configuration

# Port for the remote command server
port: 25566

# Password for authentication (change this!)
password: "your_secure_password_here"

# Maximum number of failed authentication attempts before temporary IP ban
max_failed_attempts: 5

# Ban duration in minutes after exceeding max failed attempts
ban_duration: 30 